FROM madnificent/ember:3.18.0 as builder

LABEL maintainer="info@redpencil.io"

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN ember build --environment production

FROM aatauil/fastboot-app-server:latest

COPY --from=builder /app/dist /app